export const DISPLAY_SIDE_NAV = 'DISPLAY_SIDE_NAV';
export const HIDE_BACKDROP = 'HIDE_BACKDROP';
export const INITIAL_GET_MOVIES = 'INITIAL_GET_MOVIES';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const GO_NEXT_PAGE = 'GO_NEXT_PAGE';
export const GO_PREV_PAGE = ' GO_PREV_PAGE';
export const GET_RATED_MOVIE = 'GET_RATED_MOVIE';
export const RESET_PAGINATION = 'RESET_PAGINATION';

export const SEARCH_FOR_MOVIE = 'SEARCH_FOR_MOVIE';
export const GET_USER_INPUT = 'GET_USER_INPUT';
export const MOVIE_SEARCH = 'MOVIE_SEARCH';

export const GET_GENRE_LIST = 'GET_GENRE_LIST';
export const GET_LINK = 'GET_LINK';

export const CLEAR_MOVIE = 'CLEAR_MOVIE';
export const GET_MOVIE_TRAILER = 'GET_MOVIDE_TRAILER';
export const ERROR_HAS_OCCURED = 'ERROR_HAS_OCCURED'


