export const DISPLAY_SIDE_NAV = 'DISPLAY_SIDE_NAV';
export const HIDE_BACKDROP = 'HIDE_BACKDROP';

export const INITIAL_GET_MOVIES = 'INITIAL_GET_MOVIES';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const GO_NEXT_PAGE = 'GO_NEXT_PAGE';
export const GO_PREV_PAGE = ' GO_PREV_PAGE';

